---
- name: Render ASA interface configuration to file
  ansible.builtin.template:
    src: "templates/interfaces.j2"
    dest: "{{ role_path }}/output/{{ inventory_hostname }}_interfaces.cfg"

- name: Push interface configuration to ASA
  cisco.asa.asa_config:
    src: "{{ role_path }}/output/{{ inventory_hostname }}_interfaces.cfg"
  notify: save_asa_config