---
# Default variables for ASA role
admin_user: admin
admin_pass: CHANGE_ME

# Demo configuration lines (simple example). For real devices, set per-host under host_vars.
asa_config_lines:
  - "hostname ASA_DEMO"
  - "interface GigabitEthernet0/0"
  - " nameif outside"
  - " security-level 0"
  - " ip address 192.0.2.1 255.255.255.0"
  - "write memory"
