---
asa_interfaces:
  - name: "gigabitEthernet0/1"
    description: "Link to WAN - OUTSIDE"
    nameif: "outside"
    security_level: 0
    ip_address: "198.16.0.1"
    mask: "255.255.255.0"
  
  - name: "gigabitEthernet0/0"
    description: "Internal LAN - INSIDE"
    nameif: "inside"
    security_level: 100
    ip_address: "10.10.10.1"
    mask: "255.255.255.0"

asa_routes:
  - interface: "outside"
    prefix: "0.0.0.0"
    mask: "0.0.0.0"
    next_hop: "198.16.0.2"
    metric: 1
  - interface: "inside"
    prefix: "10.10.11.0"
    mask: "255.255.255.0"
    next_hop: "10.10.10.2"
    metric: 1
